services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: fov-mediamtx
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    ports:
      - "9999:9999/udp" # SRT listener
      - "8888:8888" # HLS
    restart: unless-stopped
    command: /mediamtx

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/media:/var/media
    ports:
      - "4000:4000" # API
    depends_on:
      - mediamtx
    restart: unless-stopped
    environment:
      - MEDIAMTX_HOST=mediamtx
      - MEDIAMTX_HLS_PORT=8888

  frontend:
    build:
      context: ./fov-angular
    volumes:
      - ./fov-angular:/app
      - /app/node_modules
    ports:
      - "4200:4200" # Angular dev server
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ng serve --host 0.0.0.0 --port 4200
    restart: unless-stopped
