version: "3"

services:
    nginx:
        build: ./nginx
        ports:
            - 80:80         # Port interface web
            - 1935:1935     # Port RTMP
        restart: on-failure
        networks:
            - internal_network

    backend-fov:
        build: ./fov-angular
        restart: on-failure
        networks:
            - internal_network

networks:
    internal_network:
        driver: bridge