name: Deploy Developpement - WEB-FOV

# Deploy the developpement website (dev branch) to the self-hosted deploy server

on:
  push:
    branches:
      - "dev"
      - "single-api-port"

jobs:
    Deploy-dev:
        runs-on: [ self-hosted, linux, x64, deploy ]
        steps:
        - name: "Checkout code"
          uses: actions/checkout@v4

        - name: "Create frontend env file"
          env:
            API_URL: ${{ secrets.DEPLOY_HOSTNAME }}
            TWITCH_ID: ${{ secrets.TWITCH_CLIENT_ID }}
            TWITCH_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          run: |
            cd fov-angular/src/environments/
            cp environment.example.ts environment.ts
            sed -i "s|API_URL_HERE|$API_URL|g" environment.ts
            sed -i "s|YOUR_CLIENT_ID_HERE|$TWITCH_ID|g" environment.ts
            sed -i "s|YOUR_CLIENT_SECRET_HERE|$TWITCH_SECRET|g" environment.ts

        - name: "Create backend file"
          env:
            PORT: 4000
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            FFMPEG_PATH: ${{ secrets.FFMPEG_PATH }}
            SRT_URL: ${{ secrets.DEPLOY_HOSTNAME }}
            MEDIA_ROOT: ${{ secrets.MEDIA_ROOT }}
          run: |
            cd backend
            touch .env
            echo "PORT=${PORT}" >> .env
            echo "DB_HOST=${DB_HOST}" >> .env
            echo "DB_PORT=${DB_PORT}" >> .env
            echo "DB_USER=${DB_USER}" >> .env
            echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
            echo "DB_NAME=${DB_NAME}" >> .env
            echo "FFMPEG_PATH=${FFMPEG_PATH}" >> .env
            echo "SRT_URL=${SRT_URL}" >> .env
            echo "MEDIA_ROOT=${MEDIA_ROOT}" >> .env
            ls -a

        - name: "Stop previous container"
          run: cd /home/deploy/web-deploy/dev/ && docker-compose down
          continue-on-error: true

        - name: "Clean docker images"
          run: cd /home/deploy/web-deploy/dev/ && docker system prune -f

        - name: "Remove folder content"
          run: rm -rf /home/deploy/web-deploy/dev/
          continue-on-error: true

        - name: "Copy repository"
          run: mkdir -p /home/deploy/web-deploy/dev/ && cp -r . /home/deploy/web-deploy/dev/

        - name: "Run the docker compose stack"
          run: cd /home/deploy/web-deploy/dev/ && docker-compose up -d --no-deps --build --force-recreate
