name: Deploy Developpement - WEB-FOV

# Deploy the developpement website (dev branch) to the self-hosted deploy server

on:
  push:
    branches:
      - "dev"
      - "87-fix-déploiement-master-site-fov"

jobs:
    Deploy-dev:
        runs-on: [ self-hosted, linux, x64, deploy ]
        environment:
          name: Deploy-Dev-Selfhost

        steps:
        - name: "Checkout code"
          uses: actions/checkout@v5

        - name: "Create .env file"
          run: |
            cat <<EOF > .env
            # Backend Variables
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            API_HOSTNAME=${{vars.API_HOSTNAME}}
            SRT_URL=${{vars.SRT_ENDPOINT_HOSTNAME}}
            # Frontend Variables
            API_URL=${{ vars.API_FULL_URL }}
            TWITCH_ID=${{ secrets.TWITCH_ID }}
            TWITCH_SECRET=${{ secrets.TWITCH_SECRET }}
            EOF

        - name: "Stop previous container"
          run: cd /home/deploy/web-deploy/dev/ && docker-compose down
          continue-on-error: true

        - name: "Clean docker images"
          run: cd /home/deploy/web-deploy/dev/ && docker system prune -f

        - name: "Remove folder content"
          run: rm -rf /home/deploy/web-deploy/dev/
          continue-on-error: true

        - name: "Copy repository"
          run: mkdir -p /home/deploy/web-deploy/dev/ && cp -r . /home/deploy/web-deploy/dev/

        - name: "Run the docker compose stack"
          run: cd /home/deploy/web-deploy/dev/ && docker-compose up -d --no-deps --build --force-recreate
