name: Deploy Public - WEB-FOV

# Deploy the release website (main branch) to the epitech vm "Public-Deploy"

on:
  push:
    branches:
      - "main"
      - "87-fix-déploiement-master-site-fov"

jobs:
    Deploy-public:
        runs-on: [ self-hosted, linux, x64, public, master ]
        environment:
          name: Deploy-Main-EPITECH

        steps:
        - name: "Checkout code"
          uses: actions/checkout@v5

        - name: "Create .env file"
          run: |
            cat <<EOF > .env
            # Backend Variables
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            API_HOSTNAME=${{vars.API_HOSTNAME}}
            SRT_URL=${{vars.SRT_ENDPOINT_HOSTNAME}}
            # Frontend Variables
            API_URL=${{ vars.API_FULL_URL }}
            TWITCH_ID=${{ secrets.TWITCH_ID }}
            TWITCH_SECRET=${{ secrets.TWITCH_SECRET }}
            EOF

        - name: "Stop previous container"
          run: cd /home/debian/deploy/master && docker compose down
          continue-on-error: true

        - name: "Clean docker images"
          run: cd /home/debian/deploy/master && docker system prune -f

        - name: "Remove folder content"
          run: rm -rf /home/debian/deploy/master
          continue-on-error: true

        - name: "Copy repository"
          run: mkdir -p /home/debian/deploy/master/ && cp -r . /home/debian/deploy/master

        - name: "Run the docker compose stack"
          run: docker network inspect nginx-proxy-network >/dev/null 2>&1 || docker network create nginx-proxy-network
               cd /home/debian/deploy/master && docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build --force-recreate
